version: "3.8"

services:
  container_1:
    build: .
    container_name: container_1
    environment:
      - DISPLAY=host.docker.internal:0
      - EMAIL=${CONTAINER1_EMAIL}
      - PASSWORD=${CONTAINER1_PASSWORD}
      - PUSHPULLET_KEY=${CONTAINER1_PUSHBULLET_KEY}
    shm_size: "2g"
    deploy:
      resources:
        limits:
          memory: 2g
          cpus: "2"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: ["--email", "${CONTAINER1_EMAIL}", "--password", "${CONTAINER1_PASSWORD}", "--pushbullet-key", "${CONTAINER1_PUSHBULLET_KEY}"]

  container_2:
    build: .
    container_name: container_2
    environment:
      - DISPLAY=host.docker.internal:0
      - EMAIL=${CONTAINER2_EMAIL}
      - PASSWORD=${CONTAINER2_PASSWORD}
      - PUSHPULLET_KEY=${CONTAINER2_PUSHBULLET_KEY}
    shm_size: "2g"
    deploy:
      resources:
        limits:
          memory: 2g
          cpus: "2"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: ["--email", "${CONTAINER2_EMAIL}", "--password", "${CONTAINER2_PASSWORD}", "--pushbullet-key", "${CONTAINER2_PUSHBULLET_KEY}"]

  container_3:
    build: .
    container_name: container_3
    environment:
      - DISPLAY=host.docker.internal:0
      - EMAIL=${CONTAINER3_EMAIL}
      - PASSWORD=${CONTAINER3_PASSWORD}
      - PUSHPULLET_KEY=${CONTAINER3_PUSHBULLET_KEY}
    shm_size: "2g"
    deploy:
      resources:
        limits:
          memory: 2g
          cpus: "2"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: ["--email", "${CONTAINER3_EMAIL}", "--password", "${CONTAINER3_PASSWORD}", "--pushbullet-key", "${CONTAINER3_PUSHBULLET_KEY}"]
